"use client";

import React, { createContext, useContext, useState } from "react";

export type Locale = "en" | "th";

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.newArrivals": "New Arrivals",
    "nav.bags": "Bags",
    "nav.accessories": "Accessories",
    "nav.about": "About",
    "nav.search": "Search Archives...",
    "nav.products": "Products",
    "promo.shipping": "Complimentary global insured shipping on all archives",
    "promo.stores": "Stores",
    "promo.concierge": "Concierge",
    "hero.title": "Timeless\nLuxury",
    "hero.subtitle": "Curated from Tokyo",
    "hero.discover": "Discover Collection",
    "hero.slide1.title": "Eternal\nElegance",
    "hero.slide1.subtitle": "Sourced from the heart of Tokyo",
    "hero.slide2.title": "The\nArchive",
    "hero.slide2.subtitle": "Rare icons, meticulously preserved",
    "hero.slide3.title": "Tokyo\nHeritage",
    "hero.slide3.subtitle": "A standard of authenticity like no other",
    "common.category": "Category",
    "common.delivery": "Delivery",
    "common.quantity": "Quantity",
    "common.addToBag": "Add to Bag",
    "common.wishlist": "Wishlist",
    "common.share": "Share",
    "common.sku": "SKU",
    "common.reviews": "Reviews",
    "common.related": "Related Products",
    "common.freeShipping": "Free Shipping Worldwide",
    "common.scroll": "Scroll",
    "common.viewAll": "View All",
    "common.loadMore": "Load More",
    "common.items": "Items",
    "common.sort": "Sort",
    "common.filter": "Filter",
    "common.showing": "Showing",
    "common.of": "of",
    "cart.duties": "Duties",
    "cart.included": "Included",
    "cart.authVerified": "Authentic Verified",
    "accessories.timelessObjects": "Timeless Objects",
    "accessories.essentials": "Essentials",
    "accessories.description":
      "Elevate your ensemble with our curated collection of vintage jewelry and designer accessories.",
    "product.description": "Description",
    "product.additionalInfo": "Additional Information",
    "product.reviews": "Reviews",
    "product.writeReview": "Write a Review",
    "product.whyChoose": "Why choose this piece?",
    "product.materials": "Curated Materials",
    "cart.title": "Shopping Bag",
    "cart.empty": "Your bag is currently empty",
    "cart.start": "Start Shopping",
    "cart.summary": "Summary",
    "cart.checkout": "Proceed to Checkout",
    "cart.subtotal": "Subtotal",
    "cart.total": "Total",
    "cart.globalShipping": "Global Express Shipping",
    "cart.free": "Free",
    "checkout.shipping": "Shipping Details",
    "checkout.payment": "Payment Method",
    "checkout.confirmation": "Confirmation",
    "checkout.firstName": "First Name",
    "checkout.lastName": "Last Name",
    "checkout.street": "Street Address",
    "checkout.city": "City",
    "checkout.postalCode": "Postal Code",
    "checkout.country": "Country",
    "checkout.cardNumber": "Card Number",
    "checkout.expiryDate": "Expiry Date",
    "checkout.cvc": "CVC",
    "checkout.creditCard": "Credit Card",
    "checkout.back": "Back",
    "checkout.complete": "Complete Purchase",
    "checkout.orderSummary": "Order Summary",
    "checkout.secure": "SSL Secure Transaction",
    "checkout.cards": "All Major Cards Accepted",
    "footer.collections": "Collections",
    "footer.luxuryBags": "Luxury Bags",
    "footer.archivePieces": "Archive Pieces",
    "footer.limitedEdition": "Limited Edition",
    "footer.company": "MB Boutique",
    "footer.heritage": "Our Heritage",
    "footer.authenticity": "Authenticity Assurance",
    "footer.sustainability": "Sustainability",
    "footer.press": "Press",
    "footer.careers": "Careers",
    "footer.clientService": "Client Services",
    "footer.contact": "Contact Us",
    "footer.returns": "Shipping & Returns",
    "footer.sizeGuide": "Size Guide",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.termsOfSale": "Terms of Sale",
    "footer.newsletterTitle": "L'Edition",
    "footer.newsletterDesc":
      "Receive early access to private sales and new archive drops.",
    "footer.newsletterPlaceholder": "YOUR EMAIL",
    "footer.newsletterJoin": "Join",
    "footer.subscribe": "Subscribe",
    "footer.copyright": "Private Collection. Japan Licensing.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",
    "footer.emailPlaceholder": "EMAIL ADDRESS",
    "footer.subscribed": "Subscribed",
    "footer.copyrightText": "© 2025 MB Brandname Tokyo Synchronized.",
    "footer.vaultAccess": "Secure Vault Access",
    "footer.termsPrivilege": "Terms of Privilege",
    "footer.privacyProtocol": "Privacy Protocol",
    "footer.cookieManagement": "Cookie Management",
    "footer.assistance": "ASSISTANCE",
    "footer.boutique": "BOUTIQUE",
    "footer.ourStory": "Our Story",
    "footer.locations": "Locations",
    "footer.concierge": "Concierge",
    "about.legacy": "The Legacy",
    "about.mission": "Our Mission",
    "about.story1":
      "Founded in Tokyo and now serving a global clientele, MB Brandname was born out of a profound appreciation for the timeless artistry found in luxury fashion. We believe that a designer piece is not just an accessory, but a collectible archive of human creativity.",
    "about.story2":
      "Our mission is to bring the world's most coveted items from the meticulous secondhand markets of Japan directly to your doorstep, ensuring every stitch, curve, and monogram is authenticated by the industry's most rigorous experts.",
    "about.authTitle": "Authenticity First",
    "about.authDesc":
      "Every item undergoes a multi-point verification process by our in-house experts in Ginza.",
    "about.susTitle": "Sustainable Luxury",
    "about.susDesc":
      "By extending the life of luxury archives, we contribute to a more circular and responsible fashion economy.",
    "about.japanTitle": "Japan Standard",
    "about.japanDesc":
      "We leverage Japan's world-leading licensing laws for secondhand goods to guarantee zero counterfeit items.",
    "home.latestDrops": "Latest Drops",
    "home.craft": "The Craft",
    "home.craftTitle": "The Art of Collecting",
    "home.craftDesc":
      "We believe that true luxury is about curation. Our artisans meticulously restore the original beauty of each piece, ensuring that its history continues to shine.",
    "home.philosophy": "Our Philosophy",
    "home.japanDesc":
      "Shipped directly from Tokyo's premier fashion district. Each curated item has survived Japan's most rigorous standards for quality and authenticity.",
    "home.priorityShipping": "Global Priority Shipping",
    "home.priorityDesc":
      "Express Global Distribution\nDirect to your door in 3-5 days",
    "home.certifiedAuthentic": "Certified Authentic",
    "home.certifiedDesc": "Meticulously Verified\nBy Japanese Masters",
    "home.conciergeSupport": "Concierge Support",
    "home.conciergeDesc": "Dedicated Client Liaisons\nAvailable 24/7 for you",
    "home.seasonalArchive": "Seasonal Archive",
    "home.archiveMemo": "Archive Memo",
    "home.memoText":
      "True luxury is about the survival of artistry through decades.",
    "home.featured": "Featured",
    "home.authGuaranteed": "Auth Guaranteed",
    "home.premiumGrade": "Premium Grade",
    "home.meticulousRestoration": "Meticulous\nRestoration",
    "home.priority": "Priority",
    "home.directFromTokyo": "Direct from Tokyo",
    "home.fullArchive": "Full Archive",
    "home.discovery": "Discovery",
    "home.theCollection": "The Collection",
    "home.latestArrivals": "Latest\nArrivals",
    "home.viewCompleteArchive": "View Complete Archive",
    "home.drop": "DROP",
    "home.ourPromise": "Our\nPromise.",
    "home.promiseDesc":
      "With over a decade of expertise, we are dedicated to curating the finest authentic luxury items from Japan. Quality is not just a standard; it is our obsession.",
    "home.authTitle": "Authenticity",
    "home.authSub": "100% Verified by Experts",
    "home.deliveryTitle": "Delivery",
    "home.deliverySub": "Fast & Insured Worldwide",
    "home.serviceTitle": "Service",
    "home.serviceSub": "24/7 Concierge Support",
    "home.whatTheySay": "What They",
    "home.say": "Say.",
    "home.verifiedReviews": "Verified Reviews",
    "home.review1":
      "Impeccable condition, exquisite packaging. The bag looks brand new. Truly a premium experience from start to finish.",
    "home.review2":
      "Third purchase and consistently impressed. Authentication is thorough and shipping is remarkably fast. Highly recommended.",
    "home.review3":
      "The concierge service is outstanding. They helped me find the exact piece I was looking for. A true luxury shopping experience.",

    "auth.invalidEmail": "Invalid email or password",
    "auth.nameRequired": "Name is required",
    "auth.passwordLength": "Password must be at least 4 characters",
    "auth.welcome": "Welcome",
    "auth.viewCart": "View Cart",
    "auth.continueShopping": "Continue Shopping",
    "auth.welcomeTitle": "Welcome to\nMB Brandname",
    "auth.signInDesc":
      "Sign in to access exclusive offers and track your orders",
    "auth.success": "Welcome Back!",
    "auth.redirecting": "Redirecting you to homepage...",
    "auth.signIn": "Sign In",
    "auth.register": "Create Account",
    "auth.welcomeBack": "Welcome Back",
    "auth.joinArchive": "Join the Archive",
    "auth.signInAction": "Sign in to access your curated collection",
    "auth.registerAction": "Register for exclusive vault access",
    "auth.fullName": "Full Name",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.authenticate": "Authenticate",
    "auth.registerAccount": "Register Account",
    "auth.or": "Or",
    "auth.continueGoogle": "Continue with Google",
    "auth.terms":
      "By signing in, you agree to our Terms of Service and Privacy Policy",
  },
  th: {
    "nav.home": "หน้าหลัก",
    "nav.newArrivals": "สินค้ามาใหม่",
    "nav.bags": "กระเป๋าแบรนด์เนม",
    "nav.accessories": "เครื่องประดับ",
    "nav.about": "เกี่ยวกับเรา",
    "nav.search": "ค้นหาสินค้าในคลัง...",
    "nav.products": "รายการสินค้าทั้งหมด",
    "promo.shipping": "บริการจัดส่งด่วนทั่วโลกฟรี พร้อมประกันภัยสินค้า",
    "promo.stores": "ที่ตั้งบูทีค",
    "promo.concierge": "บริการผู้ช่วยส่วนบุคคล",
    "hero.title": "นิยามแห่งความหรูหรา\nไร้กาลเวลา",
    "hero.subtitle": "คัดสรรพิเศษส่งตรงจากโตเกียว",
    "hero.discover": "เลือกชมคอลเลกชัน",
    "hero.slide1.title": "ความงามที่\nสง่าผ่าเผย",
    "hero.slide1.subtitle": "คัดสรรจากศูนย์กลางแฟชั่นแห่งโตเกียว",
    "hero.slide2.title": "คลังแห่ง\nมรดกเลอค่า",
    "hero.slide2.subtitle": "ไอคอนหายากที่ได้รับการดูแลรักษาอย่างดีเยี่ยม",
    "hero.slide3.title": "มาตรฐาน\nจากญี่ปุ่น",
    "hero.slide3.subtitle": "การันตีความแท้ระดับสากลที่คุณมั่นใจ",
    "common.category": "หมวดหมู่",
    "common.delivery": "การจัดส่ง",
    "common.quantity": "จำนวน",
    "common.addToBag": "หยิบใส่ถุงช้อปปิ้ง",
    "common.wishlist": "สินค้าที่ชื่นชอบ",
    "common.share": "แชร์ข้อมูลสินค้า",
    "common.sku": "รหัสสินค้า",
    "common.reviews": "ความคิดเห็น",
    "common.related": "สินค้าที่น่าสนใจ",
    "common.freeShipping": "บริการส่งฟรีทั่วโลก",
    "common.scroll": "เลื่อนลงเพื่อชม",
    "common.viewAll": "ดูทั้งหมด",
    "common.loadMore": "แสดงเพิ่มเติม",
    "common.items": "รายการ",
    "common.sort": "จัดเรียง",
    "common.filter": "ตัวกรอง",
    "common.showing": "แสดง",
    "common.of": "จาก",
    "cart.duties": "ภาษีนำเข้า",
    "cart.included": "รวมแล้ว",
    "cart.authVerified": "รับประกันของแท้",
    "accessories.timelessObjects": "เครื่องประดับและจิวเวลรี่",
    "accessories.essentials": "Essentials",
    "accessories.description":
      "เติมเต็มสไตล์ของคุณด้วยเครื่องประดับแบรนด์เนมที่คัดสรรมาอย่างดี",
    "product.description": "รายละเอียดผลิตภัณฑ์",
    "product.additionalInfo": "ข้อมูลประกอบ",
    "product.reviews": "ความคิดเห็นผู้ซื้อ",
    "product.writeReview": "เขียนคำแนะนำ",
    "product.whyChoose": "ความโดดเด่นของชิ้นนี้",
    "product.materials": "วัสดุที่คัดสรร",
    "cart.title": "ถุงช้อปปิ้ง",
    "cart.empty": "ไม่มีสินค้าในถุงช้อปปิ้งของคุณ",
    "cart.start": "เริ่มการเลือกชม",
    "cart.summary": "สรุปรายการสั่งซื้อ",
    "cart.checkout": "ไปที่หน้าชำระเงิน",
    "cart.subtotal": "ยอดรวม",
    "cart.total": "ยอดรวมสุทธิ",
    "cart.globalShipping": "บริการขนส่งด่วนระดับโลก",
    "cart.free": "ไม่มีค่าใช้จ่าย",
    "checkout.shipping": "รายละเอียดการจัดส่ง",
    "checkout.payment": "วิธีการชำระเงิน",
    "checkout.confirmation": "ยืนยันคำสั่งซื้อ",
    "checkout.firstName": "ชื่อ",
    "checkout.lastName": "นามสกุล",
    "checkout.street": "ที่อยู่อาศัย",
    "checkout.city": "จังหวัด/เมือง",
    "checkout.postalCode": "รหัสไปรษณีย์",
    "checkout.country": "ประเทศ",
    "checkout.cardNumber": "หมายเลขบัตรเครดิต",
    "checkout.expiryDate": "วันหมดอายุ",
    "checkout.cvc": "รหัสหลังบัตร (CVC)",
    "checkout.creditCard": "บัตรเครดิต",
    "checkout.back": "ย้อนกลับ",
    "checkout.complete": "ยืนยันการชำระเงิน",
    "checkout.orderSummary": "สรุปคำสั่งซื้อ",
    "checkout.secure": "ระบบรักษาความปลอดภัย SSL ขั้นสูง",
    "checkout.cards": "รองรับบัตรเครดิตชั้นนำทุกประเภท",
    "footer.collections": "คอลเลกชัน",
    "footer.luxuryBags": "กระเป๋าแบรนด์เนม",
    "footer.archivePieces": "สินค้าหายาก",
    "footer.limitedEdition": "รุ่นจำกัดจำนวน",
    "footer.company": "MB Boutique",
    "footer.heritage": "ประวัติความเป็นมา",
    "footer.authenticity": "การรับประกันของแท้",
    "footer.sustainability": "ความยั่งยืน",
    "footer.press": "สื่อมวลชน",
    "footer.careers": "ร่วมงานกับเรา",
    "footer.clientService": "บริการดูแลลูกค้า",
    "footer.contact": "ติดต่อติดต่อฝ่ายสนับสนุน",
    "footer.returns": "การจัดส่งและการคืนสินค้า",
    "footer.sizeGuide": "คู่มือรายละเอียดขนาด",
    "footer.privacyPolicy": "นโยบายความเป็นส่วนตัว",
    "footer.termsOfSale": "เงื่อนไขข้อกำหนดการขาย",
    "footer.newsletterTitle": "L'Edition",
    "footer.newsletterDesc": "รับสิทธิพิเศษและข้อมูลสินค้าใหม่ก่อนใคร",
    "footer.newsletterPlaceholder": "ที่อยู่อีเมลของคุณ",
    "footer.newsletterJoin": "สมัครสมาชิก",
    "footer.subscribe": "ติดตามข่าวสาร",
    "footer.copyright":
      "สงวนลิขสิทธิ์ คอลเลกชันส่วนตัวภายใต้ใบอนุญาตประเทศญี่ปุ่น",
    "footer.privacy": "ความเป็นส่วนตัว",
    "footer.terms": "ข้อกำหนด",
    "footer.cookies": "คุกกี้",
    "footer.emailPlaceholder": "ที่อยู่อีเมล",
    "footer.subscribed": "ลงทะเบียนแล้ว",
    "footer.copyrightText": "© 2025 MB Brandname Tokyo Synchronized.",
    "footer.vaultAccess": "เข้าสู่ระบบนิรภัย",
    "footer.termsPrivilege": "ข้อกำหนดสิทธิพิเศษ",
    "footer.privacyProtocol": "โปรโตคอลความเป็นส่วนตัว",
    "footer.cookieManagement": "การจัดการคุกกี้",
    "footer.assistance": "ความช่วยเหลือ",
    "footer.boutique": "บูทีค",
    "footer.ourStory": "เรื่องราวของเรา",
    "footer.locations": "สถานที่ตั้ง",
    "footer.concierge": "ผู้ช่วยส่วนตัว",
    "about.legacy": "ตำนานและประวัติศาสตร์",
    "about.mission": "พันธกิจของเรา",
    "about.story1":
      "ก่อตั้งขึ้นที่กรุงโตเกียวเพื่อให้บริการลูกค้าทั่วโลก MB Brandname เกิดขึ้นจากความชื่นชมอย่างลึกซึ้งในศิลปะแฟชั่นชั้นสูง เราเชื่อว่าชิ้นงานดีไซเนอร์ไม่ได้เป็นเพียงเครื่องประดับ แต่เป็นมรดกทางความคิดสร้างสรรค์ที่ควรค่าแก่การครอบครอง",
    "about.story2":
      "พันธกิจของเราคือการนำสินค้าที่เป็นตำนานจากตลาดสินค้ามือสองที่มีมาตรฐานสูงที่สุดของญี่ปุ่นมามอบให้คุณถึงบ้าน มั่นใจได้ว่าทุกรายละเอียดและการรับรองได้รับการตรวจสอบโดยผู้เชี่ยวชาญระดับสากล",
    "about.authTitle": "ความแท้คือหัวใจ",
    "about.authDesc":
      "ทุกชิ้นงานผ่านการคัดกรองและตรวจสอบหลายขั้นตอนโดยผู้มีประสบการณ์สูงประจำย่านกินซ่า",
    "about.susTitle": "ความหรูหราที่ยั่งยืน",
    "about.susDesc":
      "เราสนับสนุนเศรษฐกิจหมุนเวียนด้วยการยืดอายุการใช้งานให้กับสินค้าแบรนด์เนมเลอค่า",
    "about.japanTitle": "มาตรฐานญี่ปุ่น",
    "about.japanDesc":
      "เราดำเนินงานภายใต้กฎหมายบริหารจัดการสินค้ามือสองที่เข้มงวดที่สุดในโลกของญี่ปุ่น เพื่อรับประกันความมั่นใจ 100%",
    "home.latestDrops": "คัดสรรสินค้ามาใหม่",
    "home.craft": "ความประณีต",
    "home.craftTitle": "ศิลปะแห่งการสะสม",
    "home.craftDesc":
      "เราเชื่อว่าความหรูหราที่แท้จริงคือการดูแลรักษา ช่างฝีมือของเราบูรณะความงามดั้งเดิมของแต่ละชิ้นด้วยความเคารพในประวัติศาสตร์",
    "home.philosophy": "ปรัชญาของเรา",
    "home.japanDesc":
      "ส่งตรงจากย่านแฟชั่นชั้นนำของโตเกียว ทุกชิ้นงานผ่านมาตรฐานที่เข้มงวดที่สุดในโลกด้านคุณภาพและความถูกต้อง",
    "home.priorityShipping": "การจัดส่งด่วนพิเศษทั่วโลก",
    "home.priorityDesc":
      "เครือข่ายขนส่งระดับสากล\nถึงมือคุณอย่างรวดเร็วภายใน 3-5 วัน",
    "home.certifiedAuthentic": "รับรองคุณภาพและความแท้",
    "home.certifiedDesc": "ตรวจสอบอย่างพิถีพิถัน\nโดยผู้เชี่ยวชาญชาวญี่ปุ่น",
    "home.conciergeSupport": "บริการผู้ช่วยส่วนบุคคล",
    "home.conciergeDesc":
      "ทีมงานดูแลลูกค้าส่วนตัว\nพร้อมดูแลคุณตลอด 24 ชั่วโมง",
    "home.seasonalArchive": "คอลเลกชันฤดูกาล",
    "home.archiveMemo": "ปรัชญาของทางร้าน",
    "home.memoText":
      "ความงามที่เหนือกาลเวลา เริ่มต้นจากการคัดสรรชิ้นงานที่มีจิตวิญญาณ",
    "home.featured": "สินค้าแนะนำ",
    "home.authGuaranteed": "การรับประกันความแท้",
    "home.premiumGrade": "เกรดพรีเมียม",
    "home.meticulousRestoration": "การบูรณะ\nอย่างพิถีพิถัน",
    "home.priority": "จัดส่งด่วน",
    "home.directFromTokyo": "3-5 วันทำการ ทั่วโลก",
    "home.fullArchive": "คลังสินค้า",
    "home.discovery": "สินค้าทั้งหมด",
    "home.theCollection": "คอลเลกชัน",
    "home.latestArrivals": "สินค้า\nเข้าใหม่",
    "home.viewCompleteArchive": "ดูสินค้าทั้งหมด",
    "home.drop": "รอบที่",
    "home.ourPromise": "คำสัญญา\nของเรา",
    "home.promiseDesc":
      "ด้วยประสบการณ์กว่า 10 ปี เรามุ่งมั่นที่จะนำเสนอสินค้าแบรนด์เนมแท้จากญี่ปุ่นที่มีคุณภาพสูงสุด ทุกชิ้นผ่านการตรวจสอบอย่างละเอียด",
    "home.authTitle": "ของแท้ 100%",
    "home.authSub": "ตรวจสอบโดยผู้เชี่ยวชาญ",
    "home.deliveryTitle": "การจัดส่ง",
    "home.deliverySub": "รวดเร็วและมีประกันภัย",
    "home.serviceTitle": "บริการ",
    "home.serviceSub": "ดูแลลูกค้า 24/7",
    "home.whatTheySay": "ลูกค้าพูดถึงเรา",
    "home.say": "",
    "home.verifiedReviews": "รีวิวจริงจากลูกค้า",
    "home.review1":
      "กระเป๋าสวยมาก สภาพเหมือนใหม่ บรรจุภัณฑ์ดีเยี่ยม ประทับใจมาก",
    "home.review2":
      "สั่งซื้อครั้งที่ 3 แล้ว ไว้ใจได้เรื่องของแท้ 100% ส่งไวมาก",
    "home.review3":
      "คุณภาพสินค้าดีเกินคาด ทีมงานให้คำแนะนำดีมาก รู้สึกเหมือนช้อปในร้านหรู",

    "auth.invalidEmail": "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
    "auth.nameRequired": "กรุณาใส่ชื่อ",
    "auth.passwordLength": "รหัสผ่านต้องมีอย่างน้อย 4 ตัวอักษร",
    "auth.welcome": "สวัสดี",
    "auth.viewCart": "ดูตะกร้า",
    "auth.continueShopping": "เลือกช็อป",
    "auth.welcomeTitle": "ยินดีต้อนรับสู่\nMB Brandname",
    "auth.signInDesc": "เข้าสู่ระบบเพื่อรับสิทธิพิเศษและติดตามคำสั่งซื้อ",
    "auth.success": "เข้าสู่ระบบสำเร็จ!",
    "auth.redirecting": "กำลังนำคุณไปหน้าหลัก...",
    "auth.signIn": "เข้าสู่ระบบ",
    "auth.register": "สมัครสมาชิก",
    "auth.welcomeBack": "ยินดีต้อนรับกลับ",
    "auth.joinArchive": "สร้างบัญชีใหม่",
    "auth.signInAction": "เข้าสู่ระบบเพื่อดำเนินการต่อ",
    "auth.registerAction": "สมัครเพื่อรับสิทธิพิเศษ",
    "auth.fullName": "ชื่อ",
    "auth.email": "อีเมล",
    "auth.password": "รหัสผ่าน",
    "auth.authenticate": "เข้าสู่ระบบ",
    "auth.registerAccount": "สมัครสมาชิก",
    "auth.or": "หรือ",
    "auth.continueGoogle": "ลงชื่อเข้าด้วย Google",
    "auth.terms":
      "การเข้าสู่ระบบหมายความว่าคุณยอมรับ เงื่อนไขการใช้งาน และ นโยบายความเป็นส่วนตัว ของเรา",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [locale, setLocale] = useState<Locale>("en");

  const t = (key: string) => {
    const currentTranslations = translations[locale] as Record<string, string>;
    return currentTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      <div className={locale === "th" ? "font-thai" : ""}>{children}</div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
